package bean;// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FlatCertificate extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static FlatCertificate getRootAsFlatCertificate(ByteBuffer _bb) { return getRootAsFlatCertificate(_bb, new FlatCertificate()); }
  public static FlatCertificate getRootAsFlatCertificate(ByteBuffer _bb, FlatCertificate obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FlatCertificate __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String version() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer versionAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer versionInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int serialNumber() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String signatureAlgo() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer signatureAlgoAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer signatureAlgoInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String issuer() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer issuerAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer issuerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }
  public int validNotAfter() { int o = __offset(12); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String holder() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer holderAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer holderInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public String holderAlgo() { int o = __offset(16); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer holderAlgoAsByteBuffer() { return __vector_as_bytebuffer(16, 1); }
  public ByteBuffer holderAlgoInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 16, 1); }
  public int blockHeight() { int o = __offset(18); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int blockPreHeight() { int o = __offset(20); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createFlatCertificate(FlatBufferBuilder builder,
      int versionOffset,
      int serialNumber,
      int signatureAlgoOffset,
      int issuerOffset,
      int validNotAfter,
      int holderOffset,
      int holderAlgoOffset,
      int blockHeight,
      int blockPreHeight) {
    builder.startTable(9);
    FlatCertificate.addBlockPreHeight(builder, blockPreHeight);
    FlatCertificate.addBlockHeight(builder, blockHeight);
    FlatCertificate.addHolderAlgo(builder, holderAlgoOffset);
    FlatCertificate.addHolder(builder, holderOffset);
    FlatCertificate.addValidNotAfter(builder, validNotAfter);
    FlatCertificate.addIssuer(builder, issuerOffset);
    FlatCertificate.addSignatureAlgo(builder, signatureAlgoOffset);
    FlatCertificate.addSerialNumber(builder, serialNumber);
    FlatCertificate.addVersion(builder, versionOffset);
    return FlatCertificate.endFlatCertificate(builder);
  }

  public static void startFlatCertificate(FlatBufferBuilder builder) { builder.startTable(9); }
  public static void addVersion(FlatBufferBuilder builder, int versionOffset) { builder.addOffset(0, versionOffset, 0); }
  public static void addSerialNumber(FlatBufferBuilder builder, int serialNumber) { builder.addInt(1, serialNumber, 0); }
  public static void addSignatureAlgo(FlatBufferBuilder builder, int signatureAlgoOffset) { builder.addOffset(2, signatureAlgoOffset, 0); }
  public static void addIssuer(FlatBufferBuilder builder, int issuerOffset) { builder.addOffset(3, issuerOffset, 0); }
  public static void addValidNotAfter(FlatBufferBuilder builder, int validNotAfter) { builder.addInt(4, validNotAfter, 0); }
  public static void addHolder(FlatBufferBuilder builder, int holderOffset) { builder.addOffset(5, holderOffset, 0); }
  public static void addHolderAlgo(FlatBufferBuilder builder, int holderAlgoOffset) { builder.addOffset(6, holderAlgoOffset, 0); }
  public static void addBlockHeight(FlatBufferBuilder builder, int blockHeight) { builder.addInt(7, blockHeight, 0); }
  public static void addBlockPreHeight(FlatBufferBuilder builder, int blockPreHeight) { builder.addInt(8, blockPreHeight, 0); }
  public static int endFlatCertificate(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FlatCertificate get(int j) { return get(new FlatCertificate(), j); }
    public FlatCertificate get(FlatCertificate obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

