package bean;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_certificate.proto

// Protobuf Java Version: 3.25.3
public final class ProtoCertificateOuterClass {
  private ProtoCertificateOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoCertificateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoCertificate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    String getVersion();
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>int32 serial_number = 2;</code>
     * @return The serialNumber.
     */
    int getSerialNumber();

    /**
     * <code>string signature_algo = 3;</code>
     * @return The signatureAlgo.
     */
    String getSignatureAlgo();
    /**
     * <code>string signature_algo = 3;</code>
     * @return The bytes for signatureAlgo.
     */
    com.google.protobuf.ByteString
        getSignatureAlgoBytes();

    /**
     * <code>string issuer = 4;</code>
     * @return The issuer.
     */
    String getIssuer();
    /**
     * <code>string issuer = 4;</code>
     * @return The bytes for issuer.
     */
    com.google.protobuf.ByteString
        getIssuerBytes();

    /**
     * <code>int32 valid_not_after = 5;</code>
     * @return The validNotAfter.
     */
    int getValidNotAfter();

    /**
     * <code>string holder = 6;</code>
     * @return The holder.
     */
    String getHolder();
    /**
     * <code>string holder = 6;</code>
     * @return The bytes for holder.
     */
    com.google.protobuf.ByteString
        getHolderBytes();

    /**
     * <code>string holder_algo = 7;</code>
     * @return The holderAlgo.
     */
    String getHolderAlgo();
    /**
     * <code>string holder_algo = 7;</code>
     * @return The bytes for holderAlgo.
     */
    com.google.protobuf.ByteString
        getHolderAlgoBytes();

    /**
     * <code>int32 block_height = 8;</code>
     * @return The blockHeight.
     */
    int getBlockHeight();

    /**
     * <code>int32 block_pre_height = 9;</code>
     * @return The blockPreHeight.
     */
    int getBlockPreHeight();
  }
  /**
   * Protobuf type {@code ProtoCertificate}
   */
  public static final class ProtoCertificate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtoCertificate)
      ProtoCertificateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoCertificate.newBuilder() to construct.
    private ProtoCertificate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoCertificate() {
      version_ = "";
      signatureAlgo_ = "";
      issuer_ = "";
      holder_ = "";
      holderAlgo_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtoCertificate();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoCertificateOuterClass.internal_static_ProtoCertificate_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoCertificateOuterClass.internal_static_ProtoCertificate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoCertificate.class, Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object version_ = "";
    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    @Override
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    @Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERIAL_NUMBER_FIELD_NUMBER = 2;
    private int serialNumber_ = 0;
    /**
     * <code>int32 serial_number = 2;</code>
     * @return The serialNumber.
     */
    @Override
    public int getSerialNumber() {
      return serialNumber_;
    }

    public static final int SIGNATURE_ALGO_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object signatureAlgo_ = "";
    /**
     * <code>string signature_algo = 3;</code>
     * @return The signatureAlgo.
     */
    @Override
    public String getSignatureAlgo() {
      Object ref = signatureAlgo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signatureAlgo_ = s;
        return s;
      }
    }
    /**
     * <code>string signature_algo = 3;</code>
     * @return The bytes for signatureAlgo.
     */
    @Override
    public com.google.protobuf.ByteString
        getSignatureAlgoBytes() {
      Object ref = signatureAlgo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signatureAlgo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSUER_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object issuer_ = "";
    /**
     * <code>string issuer = 4;</code>
     * @return The issuer.
     */
    @Override
    public String getIssuer() {
      Object ref = issuer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        issuer_ = s;
        return s;
      }
    }
    /**
     * <code>string issuer = 4;</code>
     * @return The bytes for issuer.
     */
    @Override
    public com.google.protobuf.ByteString
        getIssuerBytes() {
      Object ref = issuer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        issuer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALID_NOT_AFTER_FIELD_NUMBER = 5;
    private int validNotAfter_ = 0;
    /**
     * <code>int32 valid_not_after = 5;</code>
     * @return The validNotAfter.
     */
    @Override
    public int getValidNotAfter() {
      return validNotAfter_;
    }

    public static final int HOLDER_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile Object holder_ = "";
    /**
     * <code>string holder = 6;</code>
     * @return The holder.
     */
    @Override
    public String getHolder() {
      Object ref = holder_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        holder_ = s;
        return s;
      }
    }
    /**
     * <code>string holder = 6;</code>
     * @return The bytes for holder.
     */
    @Override
    public com.google.protobuf.ByteString
        getHolderBytes() {
      Object ref = holder_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        holder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HOLDER_ALGO_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile Object holderAlgo_ = "";
    /**
     * <code>string holder_algo = 7;</code>
     * @return The holderAlgo.
     */
    @Override
    public String getHolderAlgo() {
      Object ref = holderAlgo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        holderAlgo_ = s;
        return s;
      }
    }
    /**
     * <code>string holder_algo = 7;</code>
     * @return The bytes for holderAlgo.
     */
    @Override
    public com.google.protobuf.ByteString
        getHolderAlgoBytes() {
      Object ref = holderAlgo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        holderAlgo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOCK_HEIGHT_FIELD_NUMBER = 8;
    private int blockHeight_ = 0;
    /**
     * <code>int32 block_height = 8;</code>
     * @return The blockHeight.
     */
    @Override
    public int getBlockHeight() {
      return blockHeight_;
    }

    public static final int BLOCK_PRE_HEIGHT_FIELD_NUMBER = 9;
    private int blockPreHeight_ = 0;
    /**
     * <code>int32 block_pre_height = 9;</code>
     * @return The blockPreHeight.
     */
    @Override
    public int getBlockPreHeight() {
      return blockPreHeight_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
      }
      if (serialNumber_ != 0) {
        output.writeInt32(2, serialNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signatureAlgo_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, signatureAlgo_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(issuer_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, issuer_);
      }
      if (validNotAfter_ != 0) {
        output.writeInt32(5, validNotAfter_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(holder_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, holder_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(holderAlgo_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, holderAlgo_);
      }
      if (blockHeight_ != 0) {
        output.writeInt32(8, blockHeight_);
      }
      if (blockPreHeight_ != 0) {
        output.writeInt32(9, blockPreHeight_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
      }
      if (serialNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serialNumber_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signatureAlgo_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, signatureAlgo_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(issuer_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, issuer_);
      }
      if (validNotAfter_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, validNotAfter_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(holder_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, holder_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(holderAlgo_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, holderAlgo_);
      }
      if (blockHeight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, blockHeight_);
      }
      if (blockPreHeight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, blockPreHeight_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoCertificate)) {
        return super.equals(obj);
      }
      ProtoCertificate other = (ProtoCertificate) obj;

      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (getSerialNumber()
          != other.getSerialNumber()) return false;
      if (!getSignatureAlgo()
          .equals(other.getSignatureAlgo())) return false;
      if (!getIssuer()
          .equals(other.getIssuer())) return false;
      if (getValidNotAfter()
          != other.getValidNotAfter()) return false;
      if (!getHolder()
          .equals(other.getHolder())) return false;
      if (!getHolderAlgo()
          .equals(other.getHolderAlgo())) return false;
      if (getBlockHeight()
          != other.getBlockHeight()) return false;
      if (getBlockPreHeight()
          != other.getBlockPreHeight()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + SERIAL_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getSerialNumber();
      hash = (37 * hash) + SIGNATURE_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + getSignatureAlgo().hashCode();
      hash = (37 * hash) + ISSUER_FIELD_NUMBER;
      hash = (53 * hash) + getIssuer().hashCode();
      hash = (37 * hash) + VALID_NOT_AFTER_FIELD_NUMBER;
      hash = (53 * hash) + getValidNotAfter();
      hash = (37 * hash) + HOLDER_FIELD_NUMBER;
      hash = (53 * hash) + getHolder().hashCode();
      hash = (37 * hash) + HOLDER_ALGO_FIELD_NUMBER;
      hash = (53 * hash) + getHolderAlgo().hashCode();
      hash = (37 * hash) + BLOCK_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getBlockHeight();
      hash = (37 * hash) + BLOCK_PRE_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getBlockPreHeight();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoCertificate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoCertificate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoCertificate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoCertificate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoCertificate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoCertificate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoCertificate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoCertificate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProtoCertificate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ProtoCertificate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoCertificate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoCertificate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoCertificate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoCertificate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoCertificate)
        ProtoCertificateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoCertificateOuterClass.internal_static_ProtoCertificate_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoCertificateOuterClass.internal_static_ProtoCertificate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoCertificate.class, Builder.class);
      }

      // Construct using ProtoCertificateOuterClass.ProtoCertificate.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        version_ = "";
        serialNumber_ = 0;
        signatureAlgo_ = "";
        issuer_ = "";
        validNotAfter_ = 0;
        holder_ = "";
        holderAlgo_ = "";
        blockHeight_ = 0;
        blockPreHeight_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoCertificateOuterClass.internal_static_ProtoCertificate_descriptor;
      }

      @Override
      public ProtoCertificate getDefaultInstanceForType() {
        return ProtoCertificate.getDefaultInstance();
      }

      @Override
      public ProtoCertificate build() {
        ProtoCertificate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ProtoCertificate buildPartial() {
        ProtoCertificate result = new ProtoCertificate(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ProtoCertificate result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serialNumber_ = serialNumber_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.signatureAlgo_ = signatureAlgo_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.issuer_ = issuer_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.validNotAfter_ = validNotAfter_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.holder_ = holder_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.holderAlgo_ = holderAlgo_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.blockHeight_ = blockHeight_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.blockPreHeight_ = blockPreHeight_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoCertificate) {
          return mergeFrom((ProtoCertificate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoCertificate other) {
        if (other == ProtoCertificate.getDefaultInstance()) return this;
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getSerialNumber() != 0) {
          setSerialNumber(other.getSerialNumber());
        }
        if (!other.getSignatureAlgo().isEmpty()) {
          signatureAlgo_ = other.signatureAlgo_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getIssuer().isEmpty()) {
          issuer_ = other.issuer_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getValidNotAfter() != 0) {
          setValidNotAfter(other.getValidNotAfter());
        }
        if (!other.getHolder().isEmpty()) {
          holder_ = other.holder_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getHolderAlgo().isEmpty()) {
          holderAlgo_ = other.holderAlgo_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getBlockHeight() != 0) {
          setBlockHeight(other.getBlockHeight());
        }
        if (other.getBlockPreHeight() != 0) {
          setBlockPreHeight(other.getBlockPreHeight());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                version_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                serialNumber_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                signatureAlgo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                issuer_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                validNotAfter_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 50: {
                holder_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                holderAlgo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                blockHeight_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                blockPreHeight_ = input.readInt32();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object version_ = "";
      /**
       * <code>string version = 1;</code>
       * @return The version.
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string version = 1;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        version_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        version_ = getDefaultInstance().getVersion();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        version_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int serialNumber_ ;
      /**
       * <code>int32 serial_number = 2;</code>
       * @return The serialNumber.
       */
      @Override
      public int getSerialNumber() {
        return serialNumber_;
      }
      /**
       * <code>int32 serial_number = 2;</code>
       * @param value The serialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSerialNumber(int value) {

        serialNumber_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serial_number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerialNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serialNumber_ = 0;
        onChanged();
        return this;
      }

      private Object signatureAlgo_ = "";
      /**
       * <code>string signature_algo = 3;</code>
       * @return The signatureAlgo.
       */
      public String getSignatureAlgo() {
        Object ref = signatureAlgo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          signatureAlgo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string signature_algo = 3;</code>
       * @return The bytes for signatureAlgo.
       */
      public com.google.protobuf.ByteString
          getSignatureAlgoBytes() {
        Object ref = signatureAlgo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          signatureAlgo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signature_algo = 3;</code>
       * @param value The signatureAlgo to set.
       * @return This builder for chaining.
       */
      public Builder setSignatureAlgo(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        signatureAlgo_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string signature_algo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignatureAlgo() {
        signatureAlgo_ = getDefaultInstance().getSignatureAlgo();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string signature_algo = 3;</code>
       * @param value The bytes for signatureAlgo to set.
       * @return This builder for chaining.
       */
      public Builder setSignatureAlgoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        signatureAlgo_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private Object issuer_ = "";
      /**
       * <code>string issuer = 4;</code>
       * @return The issuer.
       */
      public String getIssuer() {
        Object ref = issuer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          issuer_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string issuer = 4;</code>
       * @return The bytes for issuer.
       */
      public com.google.protobuf.ByteString
          getIssuerBytes() {
        Object ref = issuer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          issuer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string issuer = 4;</code>
       * @param value The issuer to set.
       * @return This builder for chaining.
       */
      public Builder setIssuer(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        issuer_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string issuer = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIssuer() {
        issuer_ = getDefaultInstance().getIssuer();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string issuer = 4;</code>
       * @param value The bytes for issuer to set.
       * @return This builder for chaining.
       */
      public Builder setIssuerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        issuer_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int validNotAfter_ ;
      /**
       * <code>int32 valid_not_after = 5;</code>
       * @return The validNotAfter.
       */
      @Override
      public int getValidNotAfter() {
        return validNotAfter_;
      }
      /**
       * <code>int32 valid_not_after = 5;</code>
       * @param value The validNotAfter to set.
       * @return This builder for chaining.
       */
      public Builder setValidNotAfter(int value) {

        validNotAfter_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 valid_not_after = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidNotAfter() {
        bitField0_ = (bitField0_ & ~0x00000010);
        validNotAfter_ = 0;
        onChanged();
        return this;
      }

      private Object holder_ = "";
      /**
       * <code>string holder = 6;</code>
       * @return The holder.
       */
      public String getHolder() {
        Object ref = holder_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          holder_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string holder = 6;</code>
       * @return The bytes for holder.
       */
      public com.google.protobuf.ByteString
          getHolderBytes() {
        Object ref = holder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          holder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string holder = 6;</code>
       * @param value The holder to set.
       * @return This builder for chaining.
       */
      public Builder setHolder(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        holder_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string holder = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHolder() {
        holder_ = getDefaultInstance().getHolder();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string holder = 6;</code>
       * @param value The bytes for holder to set.
       * @return This builder for chaining.
       */
      public Builder setHolderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        holder_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private Object holderAlgo_ = "";
      /**
       * <code>string holder_algo = 7;</code>
       * @return The holderAlgo.
       */
      public String getHolderAlgo() {
        Object ref = holderAlgo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          holderAlgo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string holder_algo = 7;</code>
       * @return The bytes for holderAlgo.
       */
      public com.google.protobuf.ByteString
          getHolderAlgoBytes() {
        Object ref = holderAlgo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          holderAlgo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string holder_algo = 7;</code>
       * @param value The holderAlgo to set.
       * @return This builder for chaining.
       */
      public Builder setHolderAlgo(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        holderAlgo_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string holder_algo = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearHolderAlgo() {
        holderAlgo_ = getDefaultInstance().getHolderAlgo();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string holder_algo = 7;</code>
       * @param value The bytes for holderAlgo to set.
       * @return This builder for chaining.
       */
      public Builder setHolderAlgoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        holderAlgo_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private int blockHeight_ ;
      /**
       * <code>int32 block_height = 8;</code>
       * @return The blockHeight.
       */
      @Override
      public int getBlockHeight() {
        return blockHeight_;
      }
      /**
       * <code>int32 block_height = 8;</code>
       * @param value The blockHeight to set.
       * @return This builder for chaining.
       */
      public Builder setBlockHeight(int value) {

        blockHeight_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int32 block_height = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockHeight() {
        bitField0_ = (bitField0_ & ~0x00000080);
        blockHeight_ = 0;
        onChanged();
        return this;
      }

      private int blockPreHeight_ ;
      /**
       * <code>int32 block_pre_height = 9;</code>
       * @return The blockPreHeight.
       */
      @Override
      public int getBlockPreHeight() {
        return blockPreHeight_;
      }
      /**
       * <code>int32 block_pre_height = 9;</code>
       * @param value The blockPreHeight to set.
       * @return This builder for chaining.
       */
      public Builder setBlockPreHeight(int value) {

        blockPreHeight_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>int32 block_pre_height = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockPreHeight() {
        bitField0_ = (bitField0_ & ~0x00000100);
        blockPreHeight_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtoCertificate)
    }

    // @@protoc_insertion_point(class_scope:ProtoCertificate)
    private static final ProtoCertificate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoCertificate();
    }

    public static ProtoCertificate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoCertificate>
        PARSER = new com.google.protobuf.AbstractParser<ProtoCertificate>() {
      @Override
      public ProtoCertificate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProtoCertificate> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoCertificate> getParserForType() {
      return PARSER;
    }

    @Override
    public ProtoCertificate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoCertificate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoCertificate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027proto_certificate.proto\"\320\001\n\020ProtoCerti" +
      "ficate\022\017\n\007version\030\001 \001(\t\022\025\n\rserial_number" +
      "\030\002 \001(\005\022\026\n\016signature_algo\030\003 \001(\t\022\016\n\006issuer" +
      "\030\004 \001(\t\022\027\n\017valid_not_after\030\005 \001(\005\022\016\n\006holde" +
      "r\030\006 \001(\t\022\023\n\013holder_algo\030\007 \001(\t\022\024\n\014block_he" +
      "ight\030\010 \001(\005\022\030\n\020block_pre_height\030\t \001(\005b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoCertificate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoCertificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoCertificate_descriptor,
        new String[] { "Version", "SerialNumber", "SignatureAlgo", "Issuer", "ValidNotAfter", "Holder", "HolderAlgo", "BlockHeight", "BlockPreHeight", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
